#pragma once

#define IDD_USER_BASE						(WM_USER+3000)
#define IDD_SHOW_VIEW_SRC					(IDD_USER_BASE+0)
#define IDD_SHOW_VIEW_ALM					(IDD_USER_BASE+1)
#define IDD_SHOW_VIEW_EPH					(IDD_USER_BASE+2)
#define IDD_SHOW_VIEW_ION					(IDD_USER_BASE+3)
#define IDD_SHOW_VIEW_JAL					(IDD_USER_BASE+4)
#define IDD_SHOW_VIEW_POS					(IDD_USER_BASE+5)
#define IDD_SHOW_VIEW_RAN					(IDD_USER_BASE+6)
#define IDD_SHOW_VIEW_SIV					(IDD_USER_BASE+7)
#define IDD_SHOW_VIEW_GBS					(IDD_USER_BASE+8)
#define IDD_SHOW_VIEW_XPV					(IDD_USER_BASE+9)
#define IDD_SHOW_VIEW_STA					(IDD_USER_BASE+10)
#define IDD_SHOW_VIEW_TIM					(IDD_USER_BASE+11)
#define IDD_SHOW_VIEW_VEL					(IDD_USER_BASE+12)
#define IDD_SHOW_VIEW_CHA					(IDD_USER_BASE+13)

#define IDD_DRAW_VIEW_POS					(IDD_USER_BASE+14)
#define IDD_DRAW_VIEW_RAN					(IDD_USER_BASE+15)

#define IDD_SHOW_VIEW_GGA_POS               (IDD_USER_BASE+16)

#define IDD_SHOW_VIEW_SKY					(IDD_USER_BASE+20)//星空图
#define IDD_SHOW_VIEW_SNR					(IDD_USER_BASE+21)//信号强度
#define IDD_SHOW_VIEW_GPS_SNR				(IDD_USER_BASE+24)//GPS信号强度
#define IDD_SHOW_VIEW_GA_SNR                (IDD_USER_BASE+25)//伽利略信号强度
#define IDD_SHOW_VIEW_GL_SNR                (IDD_USER_BASE+26)//GLONASS信号强度

#define IDD_SHOW_VIEW_TEST					(IDD_USER_BASE+22)//电文页面播发顺序和历书播发顺序
#define IDD_SHOW_VIEW_CHD					(IDD_USER_BASE+23)//信道译码信息




#define MSG_PLAY_FILE_STOP					(IDD_USER_BASE+100)//信号强度